### ISSUE TITLE
Can't run styleguide

### ISSUE THREAD

**Issue by jasonmarkperez** [alanbsmith/component-library-starter#2] opened 2018-03-17 02:21 UTC
## EXPECTED BEHAVIOR
Building the library works fine, but trying to run the styleguide fails

## ACTUAL BEHAVIOR
```
Module parse failed: Unexpected token (13:2)
You may need an appropriate loader to handle this file type.
|
| const modifierConfig = {
|   ...fontColors,
|   ...fontSizes,
|   ...fontStyles,
```

## STEPS TO REPRODUCE
Clone repo
Run yarn or npm install
Run yarn styleguide

## SUGGESTED SOLUTION
It seems to be a problem with the spread operator being used here, digging around it may be a problem with react-styleguidist and how they are using webpack/babel, but I'm not certain.

**Comment by jasonmarkperez** [comment] 2018-03-19 04:23
It seems like react-styleguidist is not picking up the webpack config.
I was able to resolve by adding:
`  webpackConfig: require('./webpack.config.js')`
to the styleguide.config.js

**Comment by alanbsmith** [comment] 2018-03-30 18:16
@jasonmarkperez Hey, sorry I missed this notification. That error usually pops up when `stage0` isn't included in the `.bablerc`, so your solution makes sense, but you shouldn't have to specify the webpack config if it's at the root of your project. See here: https://react-styleguidist.js.org/docs/webpack.html#reusing-your-projects-webpack-config

I'm glad you found a solution, but as I'm not able to reproduce this, I'm going to close the issue. Feel free to reopen if you'd like to discuss further though.

**Closed as completed** 2018-03-30 18:16 UTC
